import numpy as np

# path to snakemake-slurm config
# /home/hblee/snakemake_slurm/testv8/profile_cpu
# snakemake --profile=/path/to/profile
#
# tree simulation setting
sample_size = np.array([2000, 5000, 10000, 20000, 50000, 100000])
ts_pattern = "tree_sequences/ts_n{num_individuals}.ts"
tree_sequences = expand(ts_pattern,
			 			num_individuals = sample_size)

# time testing
vc_pattern = "variance_components/vc_n{num_individuals}.npy"
vcs = expand(vc_pattern,
		  	 num_individuals = sample_size)

# figure
fig_pattern = "figs/estimation_n{num_individuals}.svg"
figs = expand(fig_pattern,
			  num_individuals = sample_size)


# ---
rule all:
	input:
		figs

# ---
rule ts:
	output:
		ts_save_path = ts_pattern	
	params:
		seq_length = 1e8,
		num_individuals = "{num_individuals}",		
	script:
		"00-sim_ts.py"
# ---
rule vc:
	input:
		ts_path = ts_pattern
	output:
		save_path = vc_pattern
	params:
		num_individuals = "{num_individuals}"
	script:
		"01-estimation.py"

# ---
rule figure:
	input:
		variance_components=vc_pattern
	output:
		save_path = fig_pattern
	params:
		num_individuals = "{num_individuals}"	
	script:
		"02-figs.py"
