import numpy as np

# path to snakemake-slurm config
# /home/hblee/snakemake_slurm/testv8/profile_cpu
# snakemake --profile=/path/to/profile
#

prefix = "spatial-simulation"
pheno_file = prefix + ".phenotypes.txt"

blup_true_pat = "blup_true/" + prefix + ".blup.it.{it}.npy"
blups_true = expand(blup_true_pat, it = np.arange(5))

blup_ped_pat = "blup_ped/" + prefix + ".blup.it.{it}.txt"
blups_ped = expand(blup_ped_pat, it = np.arange(5))

blup_infer_pat = "blup_infer/" + prefix + ".blup.it.{it}.npy"
blups_infer = expand(blup_infer_pat, it = np.arange(5))

# ---
rule all:
	input:
		blups_infer,
		blups_true,
		#blups_ped

# ---
rule blup:
	output:
		blup_true_pat
	shell:
		"python 01-tslmm_true.py --it {wildcards.it}"

# ---
rule process_pkl:
	output:
		pheno_file
	shell:
		"python 02-rconvert.py"

# ---
rule blup_ped:
	output:
		out_name=blup_ped_pat
	script:
		"03-pedigreelmm.R"

# ---
rule infer:
	output:
		blup_infer_pat
	shell:
		"python 04-tslmm_infer.py --it {wildcards.it}"

